# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: gpu-runner
    # Cloud Provider: GCP
    cloud: gcp
    # Cheapest GPU on GCP
    gpu: nvidia-tesla-t4
    # Cheapest VM on GCP, with GPU attachable
    instance_type: n1-standard-1
    # Custom image with NVIDIA drivers installed on Ubuntu-20.4
    # to reduce provision time
    # Format => project_name:image_name
    machine_image: sgkit-dev:cirun-nvidia
    region:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f
      - us-east1-c
      - us-east1-d
      - us-east4-a
      - us-east4-b
      - us-east4-c
      - us-west1-a
      - us-west1-b
      - us-west2-b
      - us-west2-c
      - us-west4-a
      - us-west4-b
    # preemptible instances seems quite less reliable.
    preemptible: false
    # Adding the GPU label, this matches the runs-on param from .github/workflows/build-gpu.yml
    labels:
      - cirun-gpu-runner
