queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - status-success=build (3.10)
      - status-success=build (3.11)
      - status-success=win_build (3.10)
      - approved-reviews-by=@sgkit-dev/committers
      - "#approved-reviews-by>=1"
      - label=auto-merge
    merge_conditions:
      - base=main
      - status-success=build (3.10)
      - status-success=build (3.11)
      - status-success=win_build (3.10)
      - approved-reviews-by=@sgkit-dev/committers
      - "#approved-reviews-by>=1"
      - label=auto-merge
    merge_method: rebase

pull_request_rules:
  - name: deleting merged branch
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ping author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This PR has conflicts, @{{author}} please rebase and push updated version 🙏
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: automatic merge
    conditions: []
    actions:
      queue:
