name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libcurl4-openssl-dev  # Needed for htslib (via cyvcf2)
        sudo apt install libgsl-dev   # Needed for msprime < 1.0. Binary wheels include GSL for >= 1.0
        sudo apt install graphviz  # Needed for documentation
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt -r requirements-doc.txt
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
    - name: Check for Sphinx doc warnings
      run: |
        cd docs
        make html SPHINXOPTS="-W --keep-going"
    - name: Test with pytest and coverage
      run: |
        pytest -v --cov=sgkit --cov-report=term-missing
    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        codecov
