name: Build NumPy 2

on:
  push:
  pull_request:

jobs:
  build:
    # Scheduled runs only on the origin org
    if: (github.event_name == 'schedule' && github.repository_owner == 'sgkit-dev') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-numpy2.txt -r requirements-numpy2-dev.txt
        # update bio2zarr for NumPy 2, see https://github.com/sgkit-dev/bio2zarr/issues/256
        pip install -U 'numpy<2.1' -U git+https://github.com/sgkit-dev/bio2zarr.git
    # - name: Run pre-commit
    #   uses: pre-commit/action@v2.0.0
    - name: Test with pytest (numba jit disabled)
      env:
        NUMBA_DISABLE_JIT: 1
      run: |
        # avoid guvectorized functions #1194
        pytest -v sgkit/tests/test_pedigree.py
    - name: Test with pytest and coverage
      run: |
        pytest -v --cov=sgkit --cov-report=term-missing
