name: Build NumPy 1

on:
  push:
  pull_request:

jobs:
  build:
    # Scheduled runs only on the origin org
    if: (github.event_name == 'schedule' && github.repository_owner == 'sgkit-dev') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-numpy1.txt -r requirements-numpy1-dev.txt
    # - name: Run pre-commit
    #   uses: pre-commit/action@v2.0.0
    - name: Test with pytest and coverage
      run: |
        pytest -v --cov=sgkit --cov-report=term-missing
