name: Upstream

on:
  push:
  schedule:
    - cron: "0 1 * * *"
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    # This workflow only runs on the origin org
    if: github.repository_owner == 'sgkit-dev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps and sgkit
      run: |
        python -m pip install --upgrade pip packaging
        python .github/scripts/upstream_install.py

    - name: Test with pytest
      run: |
        python -m pip freeze
        pytest -v
