name: Windows

on:
  push:
  pull_request:
  schedule:
    # Run at the end of every day
    - cron: "0 0 * * *"

jobs:
  win_build:
    # Scheduled runs only on the origin org
    if: (github.event_name == 'schedule' && github.repository_owner == 'pystatgen') || (github.event_name != 'schedule')
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Miniconda with Python version ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge,numba
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      # activate conda
      shell: bash -l {0}
      # conda can't install all dev tools, so we need to split it between conda and pip
      run: |
        conda install --file requirements.txt msprime
        pip install -r requirements-dev.txt
    - name: Test with pytest and coverage
      # activate conda
      shell: bash -l {0}
      run: |
        pytest -v
