name: Windows

on:
  push:
  pull_request:
  schedule:
    # Run at the end of every day
    - cron: "0 0 * * *"

jobs:
  win_build:
    # Scheduled runs only on the origin org
    if: (github.event_name == 'schedule' && github.repository_owner == 'sgkit-dev') || (github.event_name != 'schedule')
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Test with pytest
      # To avoid: 'UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1'
      env:
        OMP_NUM_THREADS: 1
      run: |
        pytest -v
