name: Windows

on: [push, pull_request]

jobs:
  win_build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Miniconda with Python version ${{ matrix.python-version }}
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      # activate conda
      shell: bash -l {0}
      # conda can't install all dev tools, so we need to split it between conda and pip
      run: |
        conda install --file requirements.txt msprime
        pip install -r requirements-dev.txt
    - name: Test with pytest and coverage
      # activate conda
      shell: bash -l {0}
      run: |
        pytest -v
